[grpc]
address = "0.0.0.0:18000"

[grpc.services.storageprovider]
driver = "local"
mount_path = "/reva"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
data_server_url = "http://iop-storageprovider-reva:18001/data"
[grpc.services.storageprovider.mimetypes]
".zmd" = "application/compressed-markdown"

[http]
address = "0.0.0.0:18001"

[http.services.dataprovider]
driver = "local"
