kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: gocdb-data
spec:
    storageClassName: cephfs
    accessModes:
      - ReadWriteMany
    resources:
        requests:
            storage: 8Gi
