kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: iop-data
spec:
    storageClassName: cephfs
    accessModes:
      - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
