kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: mentix-data
spec:
    storageClassName: cephfs
    accessModes:
      - ReadWriteMany
    resources:
        requests:
            storage: 500Mi
