kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: prom-shared-data
spec:
    storageClassName: cephfs
    accessModes:
      - ReadWriteMany
    resources:
        requests:
            storage: 100Mi
