# -- Metrics --

- job_name: 'sciencemesh-metrics'
  scheme: 'https'

  file_sd_configs:
  - refresh_interval: 30s
    files:
      - '/tmp/sciencemesh/svc_metrics.json'

  honor_labels: true
  relabel_configs:
    - source_labels: [__meta_mentix_path]
      target_label: __metrics_path__
    - source_labels: [__meta_mentix_scheme]
      target_label: __scheme__
    - source_labels: [__meta_mentix_site]
      target_label: site
    - source_labels: [__meta_mentix_site_id]
      target_label: site_id
    - source_labels: [__meta_mentix_site_country]
      target_label: country
    - source_labels: [__meta_mentix_type]
      target_label: service_type

# -- Health Checks --

- job_name: 'sciencemesh-hcheck-http-ping'
  scheme: 'http'
  metrics_path: /probe

  params:
    module: [http_ping]

  file_sd_configs:
  - refresh_interval: 30s
    files:
      - '/tmp/sciencemesh/svc_revad.json'
      - '/tmp/sciencemesh/svc_meshdir.json'

  relabel_configs:
    - source_labels: [__meta_mentix_url]
      target_label: __param_target
    - source_labels: [__meta_mentix_host]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter-prometheus-blackbox-exporter:9115
    - source_labels: [__meta_mentix_site]
      target_label: site
    - source_labels: [__meta_mentix_site_id]
      target_label: site_id
    - source_labels: [__meta_mentix_site_country]
      target_label: country
    - source_labels: [__meta_mentix_type]
      target_label: service_type

- job_name: 'sciencemesh-hcheck-iop-login'
  scheme: 'http'
  metrics_path: /probe

  params:
    module: [iop_login]

  file_sd_configs:
  - refresh_interval: 30s
    files:
      - '/tmp/sciencemesh/svc_gateway.json'

  relabel_configs:
    - source_labels: [__meta_mentix_host, __meta_mentix_port]
      separator: ':'
      target_label: __param_target
    - source_labels: [__meta_mentix_host]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter-prometheus-blackbox-exporter:9115
    - source_labels: [__meta_mentix_site]
      target_label: site
    - source_labels: [__meta_mentix_site_id]
      target_label: site_id
    - source_labels: [site_id]
      target_label: __param_site
    - source_labels: [__meta_mentix_site_country]
      target_label: country
    - source_labels: [__meta_mentix_type]
      target_label: service_type
