# Dockerfile -- Webserver for GOCDB based on PHP5-Apache
#
# Development version: Does not copy HTML contents to the container (assumes the contents to be mounted as a volume)

FROM    php:5-apache
LABEL   maintainer "daniel.mueller@uni-muenster.de"
LABEL   description "Webserver container for GOCDB"

# Needed for Doctrine
RUN     mkdir -p /usr/local/doctrine
COPY    config/composer.json /usr/local/doctrine
ENV     PATH="/usr/local/doctrine/vendor/bin:${PATH}"

# Install additional dependencies etc.
RUN     apt-get update && \
        apt-get install -y unzip && \
        a2enmod rewrite && \
        docker-php-ext-install pdo_mysql mbstring && \
        pecl install timezonedb && \
        docker-php-ext-enable timezonedb && \
        cd /usr/local/doctrine && \
        curl -sS https://getcomposer.org/installer -o composer-setup.php && \
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
        composer install

# Add GOCDB as a virtual host
COPY    config/000-default.conf /etc/apache2/sites-available
# Override the default PHP settings
COPY    config/php.ini $PHP_INI_DIR/

# Copy database setup script
COPY    config/bootstrap-database.sh /usr/local/bin
