{
 "title": "Health monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sites", "label": "Sites", "query": "revad_sys_info" }
  ]
 },
 "panels": [
  {
   "title": "Site status",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_site_status{status_type=\"RESULT\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "repeat": "sites",
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 0 },
   "repeat": "sites",
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 4 },
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 12 },
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 20 },
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 24 },
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  }
 ]
}