{
 "title": "Health monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sites", "label": "Sites", "query": "revad_sys_info" }
  ]
 },
 "panels": [
  {
   "title": "Site status",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_site_status{status_type=\"RESULT\"}"
    },
    {
     "expr": "sciencemesh_hcheck_site_status{status_type=\"AVAIL\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "repeat": "sites",
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    },
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"AVAIL\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 0 },
   "repeat": "sites",
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    },
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"AVAIL\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    },
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"AVAIL\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Site summary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(status_type) (sciencemesh_hcheck_site_status{status_type=\"OK\"} / 1)",
     "legendFormat": "Healthy"
    },
    {
     "expr": "sum by(status_type) (sciencemesh_hcheck_site_status{status_type=\"WARN\"} / 2)",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum by(status_type) (sciencemesh_hcheck_site_status{status_type=\"CRIT\"} / 3)",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    },
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"AVAIL\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    },
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"AVAIL\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    },
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"AVAIL\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"RESULT\"}"
    },
    {
     "expr": "sciencemesh_hcheck_service_status{site=\"$sites\", status_type=\"AVAIL\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "probe_nagios_result{site=\"$sites\"}"
    }
   ]
  }
 ]
}