{
 "title": "ScienceMesh",
 "description": "Various ScienceMesh statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "User distribution by country",
   "type": "grafana-worldmap-panel",
   "description": "Displays the distribution of ScienceMesh users across the world",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "expr": "revad_cs3_org_sciencemesh_site_total_num_users",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Site locations",
   "type": "grafana-worldmap-panel",
   "description": "Displays the locations of all sites in the ScienceMesh",
   "gridPos": { "h": 14, "w": 9, "x": 10, "y": 0 },
   "valueName": "current",
   "targets": [
    { "expr": "revad_sys_info  ", "legendFormat": "{{site}}" }
   ]
  },
  {
   "title": "Site information",
   "type": "table",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 0 },
   "targets": [
    { "expr": "revad_sys_info", "legendFormat": "{{site}}" }
   ]
  },
  {
   "title": "Users per site",
   "type": "bargauge",
   "description": "Displays the number of users per site",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(revad_cs3_org_sciencemesh_site_total_num_users)",
     "legendFormat": "{{site}} ({{country}})"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "description": "Displays the total number of all users",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "revad_cs3_org_sciencemesh_site_total_num_users",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Storage per site",
   "type": "gauge",
   "description": "Displays the storage per site",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(revad_cs3_org_sciencemesh_site_total_amount_storage)",
     "legendFormat": "{{site}} ({{country}})"
    }
   ]
  },
  {
   "title": "Total storage",
   "type": "stat",
   "description": "Displays the total storage of all sites",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "revad_cs3_org_sciencemesh_site_total_amount_storage",
     "legendFormat": "{{site}}"
    }
   ]
  }
 ]
}