replicaCount: 1

image:
  repository: cs3org/revad
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  grpc:
    port: 19000
  http:
    port: 19001

extraVolumeMounts: []
extraVolumes: []

env: []

# https://reva.link/docs/config/
configFiles:
  revad.toml: |
    [grpc.services.gateway]
    [grpc.services.storageregistry]
    [grpc.services.storageprovider]
    [grpc.services.authprovider]
    [grpc.services.authregistry]
    [grpc.services.userprovider]
    [grpc.services.usershareprovider]
    [grpc.services.publicshareprovider]

    [http.services.dataprovider]
    [http.services.prometheus]

  users.json: |
    [
      {
        "id": {
          "opaque_id": "4c510ada-c86b-4815-8820-42cdf82c3d51",
          "idp": "http://localhost:20080"
        },
        "username": "einstein",
        "secret": "relativity",
        "mail": "einstein@example.org",
        "display_name": "Albert Einstein",
        "groups": ["sailing-lovers", "violin-haters", "physics-lovers"]
      },
      {
        "id": {
          "opaque_id": "f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c",
          "idp": "http://localhost:20080"
        },
        "username": "marie",
        "secret": "radioactivity",
        "mail": "marie@example.org",
        "display_name": "Marie Curie",
        "groups": ["radium-lovers", "polonium-lovers", "physics-lovers"]
      },
      {
        "id": {
          "opaque_id": "932b4540-8d16-481e-8ef4-588e4b6b151c",
          "idp": "http://localhost:20080"
        },
        "username": "richard",
        "secret": "superfluidity",
        "mail": "richard@example.org",
        "display_name": "Richard Feynman",
        "groups": ["quantum-lovers", "philosophy-haters", "physics-lovers"]
      }
    ]
