image:
  repository: harbor.uni-muenster.de/proxy-docker/omnivox/blackbox_exporter
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  hosts:
    - host: bbe.sciencemesh.uni-muenster.de
      paths:
          - path: /
            pathType: ImplementationSpecific
  tls:
    - secretName: sciencemesh-tls
      hosts:
        - bbe.sciencemesh.uni-muenster.de
pspEnabled: false
securityContext:
  runAsUser: 0
  runAsGroup: 0
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  allowPrivilegeEscalation: true
  capabilities:
    add: ["NET_RAW"]
config:
  # -- CONFIG --
