image:
  repository: omnivox/blackbox_exporter
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  hosts:
    - bbe.sciencemesh.uni-muenster.de
  tls:
    - secretName: sciencemesh-tls
      hosts:
        - grafana.sciencemesh.uni-muenster.de
pspEnabled: false
config:
  # -- MODULES --
