codimd:
  authentication:
    local:
      enabled: false
  connection:
    domain: sciencemesh-test.uni-muenster.de
    protocolUseSSL: true
  security:
    sessionSecret: "EiC2oasdfsahxi"
  extraEnvironmentVariables:
    CMD_ALLOW_ANONYMOUS: true
    CMD_ALLOW_ANONYMOUS_EDITS: true
    CMD_ALLOW_ANONYMOUS_VIEWS: true
    CMD_ALLOW_EMAIL_REGISTER: false
    CMD_EMAIL: false
    CMD_SAVE_WEBHOOK: https://sciencemesh-test.uni-muenster.de/wopib/save
    CMD_APPLIANCE_MODE: true
    CMD_URL_PATH: codimd
  versionCheck: false
  imageStorePersistentVolume:
    enabled: false
postgresql:
  enabled: false
mariadb:
  enabled: true
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
service:
  type: ClusterIP
  port: 6980
image:
  registry: gitlab-registry.cern.ch
  repository: authoring/notes/codimd
  tag: cernbox-integration
