url: "https://gocdb.sciencemesh.uni-muenster.de"
defaultScope: "SM"
apiKey: "nkuNKJ87fev5"
siteaccApi: "https://iop.sciencemesh.uni-muenster.de/iop/siteacc"

ingress:
  enabled: true
  hostname: gocdb.sciencemesh.uni-muenster.de
  tls:
    - secretName: sciencemesh-tls
      hosts:
        - gocdb.sciencemesh.uni-muenster.de
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

database:
  global:
    storageClass: cephfs
  primary:
    persistence:
      enabled: true
      existingClaim: gocdb-data
