# General settings
replicas: 1
service:
  type: 'NodePort'
  port: 3030
adminUser: admin
adminPassword: admin

# Grafana settings
grafana.ini:
  server:
    domain: sciencemesh-test.uni-muenster.de
    root_url: '%(protocol)s://%(domain)s/grafana'
    serve_from_sub_path: true

# Persistency
persistence:
  enabled: true
  size: 100Mi

# Plugins
plugins:
  - grafana-piechart-panel
  - grafana-worldmap-panel

# Prometheus data source
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: ScienceMesh
        type: prometheus
        url: https://sciencemesh-test.uni-muenster.de/prometheus
        access: proxy
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'sciencemesh'
      orgId: 1
      folder: 'ScienceMesh'
      type: file
      disableDeletion: true
      editable: true
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards/sciencemesh

env:
  # Adjust the proxy settings as needed
  HTTPS_PROXY: 'http://wwwproxy.uni-muenster.de:80'
  HTTP_PROXY: 'http://wwwproxy.uni-muenster.de:80'
  AUTO_PROXY: 'http://www.uni-muenster.de/proxyforce.pac'
  https_proxy: 'http://wwwproxy.uni-muenster.de:80'
  http_proxy: 'http://wwwproxy.uni-muenster.de:80'
  auto_proxy: 'http://www.uni-muenster.de/proxyforce.pac'
  NO_PROXY: 'localhost,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,.svc,10.14.20.42,10.14.20.44,10.14.20.45'
  no_proxy: 'localhost,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,.svc,10.14.20.42,10.14.20.44,10.14.20.45'
  USE_PROXY: 'yes'
  use_proxy: 'yes'
