# Image overrides
image:
  repository: harbor.uni-muenster.de/proxy-docker/grafana/grafana

initChownData:
  image:
    repository: harbor.uni-muenster.de/proxy-docker/library/busybox

# General settings
adminUser: admin
adminPassword: admin

ingress:
  enabled: true
  hosts:
    - grafana.sciencemesh.uni-muenster.de
  tls:
    - secretName: sciencemesh-tls
      hosts:
        - grafana.sciencemesh.uni-muenster.de
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://iop.sciencemesh.uni-muenster.de"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"

rbac:
  create: false
  pspEnabled: false

# Grafana settings
grafana.ini:
  server:
    domain: grafana.sciencemesh.uni-muenster.de
    root_url: '%(protocol)s://%(domain)s'
    serve_from_sub_path: false
  auth.anonymous:
    enabled: true
    org_name: ScienceMesh
    org_role: Viewer
  security:
    allow_embedding: true
  metrics:
    enabled: false

# Persistency
persistence:
  enabled: true
  storageClassName: rbd

# Plugins
plugins:
  - grafana-piechart-panel
  - grafana-worldmap-panel

# Prometheus data source
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: ScienceMesh
        type: prometheus
        url: http://prometheus-server.iop.svc
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'sciencemesh'
      orgId: 1
      folder: 'ScienceMesh'
      type: file
      disableDeletion: true
      editable: true
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards/sciencemesh
    - name: 'sciencemesh-health'
      orgId: 1
      folder: 'SciecenMesh Health'
      type: file
      disableDeletion: true
      editable: true
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards/sciencemesh-health
