# Ingress --
ingress:
  enabled: true
  services:
    http:
      hostname: iop.sciencemesh.uni-muenster.de
      path: /
      tls:
        - secretName: sciencemesh-tls
          hosts:
            - iop.sciencemesh.uni-muenster.de
    grpc:
      hostname: iop.sciencemesh.uni-muenster.de
      tls:
        - secretName: sciencemesh-tls
          hosts:
            - iop.sciencemesh.uni-muenster.de

# Reva gateway --
gateway:
  image:
    repository: omnivox/revad
  persistentVolume:
    enabled: true
    existingClaim: iop-data

  extraVolumeMounts:
    - name: scrape-configs
      mountPath: /tmp/scrapes
    - name: mentix-data
      mountPath: /tmp/mentix

  extraVolumes:
    - name: scrape-configs
      persistentVolumeClaim:
        claimName: prom-shared-data
    - name: mentix-data
      persistentVolumeClaim:
        claimName: mentix-data

# Home storage provider --
storageprovider-home:
  enabled: true
  image:
    repository: omnivox/revad
  service:
    grpc:
      port: 17000
    http:
      port: 17001

  persistentVolume:
    enabled: true
    existingClaim: iop-data

# Reva storage provider --
storageprovider-reva:
  enabled: true
  image:
    repository: omnivox/revad
  service:
    grpc:
      port: 18000
    http:
      port: 18001

  persistentVolume:
    enabled: true
    existingClaim: iop-data

# WOPI server --
wopiserver:
  enabled: true
  wopiserverUrl: https://iop.sciencemesh.uni-muenster.de/wopi
  config:
    appProviders:
      codeurl: http://meshapps-collabora-code:9980
      wopibridgeurl: https://iop.sciencemesh.uni-muenster.de/wopib
    cs3:
      revahost: iop-gateway:19000
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hostname: iop.sciencemesh.uni-muenster.de
    path: /wopi
    tls:
      - secretName: sciencemesh-tls
        hosts:
          - iop.sciencemesh.uni-muenster.de

  # WOPI bridge --
  wopibridge:
    enabled: true
    bridgeUrl: https://iop.sciencemesh.uni-muenster.de
    env:
      APP_ROOT: /wopib
      CODIMD_EXT_URL: https://codimd.sciencemesh.uni-muenster.de
      CODIMD_INT_URL: http://meshapps-codimd
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hostname: iop.sciencemesh.uni-muenster.de
      path: /wopib
