# Reva gateway --
gateway:
  image:
    repository: omnivox/revad # cs3org/revad
  persistentVolume:
    enabled: true
    existingClaim: iop-data

  extraVolumeMounts:
    - name: scrape-configs
      mountPath: /etc/revad/scrapes

  extraVolumes:
    - name: scrape-configs
      persistentVolumeClaim:
        claimName: prom-shared-data

  env:
    # Adjust the proxy settings as needed
    - name: HTTPS_PROXY
      value: 'http://wwwproxy.uni-muenster.de:80'
    - name: HTTP_PROXY
      value: 'http://wwwproxy.uni-muenster.de:80'
    - name: AUTO_PROXY
      value: 'http://www.uni-muenster.de/proxyforce.pac'
    - name: https_proxy
      value: 'http://wwwproxy.uni-muenster.de:80'
    - name: http_proxy
      value: 'http://wwwproxy.uni-muenster.de:80'
    - name: auto_proxy
      value: 'http://www.uni-muenster.de/proxyforce.pac'
    - name: NO_PROXY
      value: 'localhost,::1,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,.svc,10.14.20.42,10.14.20.44,10.14.20.45,iop-storageprovider-home,iop-storageprovider-reva,iop-gateway,iop-wopiserver,collabora-collabora-code'
    - name: no_proxy
      value: 'localhost,::1,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,.svc,10.14.20.42,10.14.20.44,10.14.20.45,iop-storageprovider-home,iop-storageprovider-reva,iop-gateway,iop-wopiserver,collabora-collabora-code'
    - name: USE_PROXY
      value: 'yes'
    - name: use_proxy
      value: 'yes'

# Home storage provider --
storageprovider-home:
  enabled: true
  image:
    repository: omnivox/revad # cs3org/revad
  service:
    grpc:
      port: 17000
    http:
      port: 17001

  persistentVolume:
    enabled: true
    existingClaim: iop-data

# Reva storage provider --
storageprovider-reva:
  enabled: true
  image:
    repository: omnivox/revad # cs3org/revad
  service:
    grpc:
      port: 18000
    http:
      port: 18001

  persistentVolume:
    enabled: true
    existingClaim: iop-data

# WOPI server --
wopiserver:
  enabled: true
  wopiserverUrl: https://sciencemesh-test.uni-muenster.de/wopi
  config:
    appProviders:
      codeurl: http://collabora-collabora-code:9980
    cs3:
      revahost: iop-gateway:19000
    iopsecret: 'nv7NUJc9ceHI4'
