# Reva gateway --
gateway:
#  image:
#    repository: omnivox/revad
  persistentVolume:
    enabled: true
    existingClaim: iop-data

  extraVolumeMounts:
    - name: scrape-configs
      mountPath: /etc/revad/scrapes

  extraVolumes:
    - name: scrape-configs
      persistentVolumeClaim:
        claimName: prom-shared-data

  env:
    # Adjust the proxy settings as needed
    HTTPS_PROXY: 'http://wwwproxy.uni-muenster.de:80'
    HTTP_PROXY: 'http://wwwproxy.uni-muenster.de:80'
    AUTO_PROXY: 'http://www.uni-muenster.de/proxyforce.pac'
    https_proxy: 'http://wwwproxy.uni-muenster.de:80'
    http_proxy: 'http://wwwproxy.uni-muenster.de:80'
    auto_proxy: 'http://www.uni-muenster.de/proxyforce.pac'
    NO_PROXY: 'localhost,::1,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,.svc,10.14.20.42,10.14.20.44,10.14.20.45,iop-storageprovider-home,iop-storageprovider-reva,iop-gateway,iop-wopiserver,meshapps-collabora-code'
    no_proxy: 'localhost,::1,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,.svc,10.14.20.42,10.14.20.44,10.14.20.45,iop-storageprovider-home,iop-storageprovider-reva,iop-gateway,iop-wopiserver,meshapps-collabora-code'
    USE_PROXY: 'yes'
    use_proxy: 'yes'

# Home storage provider --
storageprovider-home:
  enabled: true
#  image:
#    repository: omnivox/revad
  service:
    grpc:
      port: 17000
    http:
      port: 17001

  persistentVolume:
    enabled: true
    existingClaim: iop-data

# Reva storage provider --
storageprovider-reva:
  enabled: true
#  image:
#    repository: omnivox/revad
  service:
    grpc:
      port: 18000
    http:
      port: 18001

  persistentVolume:
    enabled: true
    existingClaim: iop-data

# WOPI server --
wopiserver:
  enabled: true
  wopiserverUrl: https://sciencemesh-test.uni-muenster.de/wopi
  config:
    appProviders:
      codeurl: http://meshapps-collabora-code:9980
    cs3:
      revahost: iop-gateway:19000
    iopsecret: 'nv7NUJc9ceHI4'
