# Reva gateway --
gateway:
  image:
    #repository: harbor.uni-muenster.de/proxy-docker/cs3org/revad
    #tag: v1.21.0
    repository: harbor.uni-muenster.de/proxy-docker/omnivox/revad
    tag: latest
  persistentVolume:
    enabled: true
    existingClaim: iop-data

  extraVolumeMounts:
    - name: scrape-configs
      mountPath: /tmp/scrapes
    - name: mentix-data
      mountPath: /tmp/mentix

  extraVolumes:
    - name: scrape-configs
      persistentVolumeClaim:
        claimName: prom-shared-data
    - name: mentix-data
      persistentVolumeClaim:
        claimName: mentix-data

  ingress:
    enabled: true
    services:
      grpc:
        hostname: iop.sciencemesh.uni-muenster.de
        path: /
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        tls:
          - secretName: sciencemesh-tls
            hosts:
              - iop.sciencemesh.uni-muenster.de
      http:
        hostname: iop.sciencemesh.uni-muenster.de
        path: /iop(/|$)(.*)
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/use-regex: "true"
          nginx.ingress.kubernetes.io/rewrite-target: /$2
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
          nginx.ingress.kubernetes.io/cors-allow-origin: "*"
          nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        tls:
          - secretName: sciencemesh-tls
            hosts:
              - iop.sciencemesh.uni-muenster.de

# Home storage provider --
storageprovider-home:
  enabled: true
  image:
    #repository: harbor.uni-muenster.de/proxy-docker/cs3org/revad
    repository: harbor.uni-muenster.de/proxy-docker/omnivox/revad
    tag: latest
  service:
    grpc:
      port: 17000
    http:
      port: 17001

  persistentVolume:
    enabled: true
    existingClaim: iop-data

# Reva storage provider --
storageprovider-reva:
  enabled: true
  image:
    #repository: harbor.uni-muenster.de/proxy-docker/cs3org/revad
    repository: harbor.uni-muenster.de/proxy-docker/omnivox/revad
    tag: latest
  service:
    grpc:
      port: 18000
    http:
      port: 18001

  persistentVolume:
    enabled: true
    existingClaim: iop-data

# WOPI server --
wopiserver:
  #enabled: true
  enabled: false
  image:
    repository: harbor.uni-muenster.de/proxy-docker/cs3org/wopiserver
  wopiserverUrl: https://iop.sciencemesh.uni-muenster.de
  config:
    appProviders:
      codeurl: http://meshapps-collabora-code:9980
      wopibridgeurl: https://iop.sciencemesh.uni-muenster.de/wopib
    cs3:
      revahost: iop-gateway:19000
    wopisecret: fwenu87z23nu
    iopsecret: vniuwn7u76354n
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hostname: iop.sciencemesh.uni-muenster.de
    path: /wopi
    tls:
      - secretName: sciencemesh-tls
        hosts:
          - iop.sciencemesh.uni-muenster.de

  # WOPI bridge --
  wopibridge:
    #enabled: true
    enabled: false
    image:
      repository: harbor.uni-muenster.de/proxy-docker/cs3org/wopibridge
    bridgeUrl: https://iop.sciencemesh.uni-muenster.de
    env:
      APP_ROOT: /wopib
      CODIMD_EXT_URL: https://codimd.sciencemesh.uni-muenster.de
      CODIMD_INT_URL: http://meshapps-codimd
    secrets:
      wbsecret: uivnwe76nucv
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hostname: iop.sciencemesh.uni-muenster.de
      path: /wopib
