# Server settings
server:
  service:
    type: 'NodePort'
    servicePort: 9090
  extraArgs:
    web.external-url: 'http://sciencemesh-test.uni-muenster.de/prometheus'  # Change this to your needs
    web.route-prefix: '/'
  extraVolumeMounts:
    - name: scrape-configs
      mountPath: /etc/prometheus/sciencemesh
  extraVolumes:
    - name: scrape-configs
      persistentVolumeClaim:
        claimName: prom-shared-data
  extraInitContainers:
    # This init container grants read and write access on the necessary mounts
    - name: init-fs
      image: busybox
      command: ['/bin/sh','-c']
      args: ['chmod -Rv 0777 /etc/prometheus/sciencemesh && chmod -Rv 0777 /data']
      securityContext:
          runAsUser: 0
          runAsNonRoot: false
      volumeMounts:
        - name: scrape-configs
          mountPath: /etc/prometheus/sciencemesh
        - name: storage-volume
          mountPath: /data

# Disable services not needed
configmapReload:
  prometheus:
    enabled: false

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: false

# ScienceMesh scrape configurations
extraScrapeConfigs: |
  # Read all ScienceMesh scrape targets from any files located in /etc/prometheus/sciencemesh/
  - job_name: 'sciencemesh'
    scheme: 'https'
    metrics_path: '/metrics'

    file_sd_configs:
    - refresh_interval: 30s
      files:
        - '/etc/prometheus/sciencemesh/*.json'
