# Server settings
server:
  service:
    type: 'NodePort'
    servicePort: 9090
  extraArgs:
    web.external-url: 'http://sciencemesh-test.uni-muenster.de/prometheus'  # Change this to your needs
    web.route-prefix: '/'
  extraVolumeMounts:
    - name: scrape-configs
      mountPath: /etc/prometheus/sciencemesh
  extraVolumes:
    - name: scrape-configs
      persistentVolumeClaim:
        claimName: prom-shared-data
  extraInitContainers:
    # This init container grants read and write access on the necessary mounts
    - name: init-fs
      image: busybox
      command: ['/bin/sh','-c']
      args: ['chmod -Rv 0777 /etc/prometheus/sciencemesh && chmod -Rv 0777 /data']
      securityContext:
          runAsUser: 0
          runAsNonRoot: false
      volumeMounts:
        - name: scrape-configs
          mountPath: /etc/prometheus/sciencemesh
        - name: storage-volume
          mountPath: /data
  env:
    # Adjust the proxy settings as needed (must also be set for the scrape config below)
    - name: HTTPS_PROXY
      value: 'http://wwwproxy.uni-muenster.de:80'
    - name: HTTP_PROXY
      value: 'http://wwwproxy.uni-muenster.de:80'
    - name: AUTO_PROXY
      value: 'http://www.uni-muenster.de/proxyforce.pac'
    - name: https_proxy
      value: 'http://wwwproxy.uni-muenster.de:80'
    - name: http_proxy
      value: 'http://wwwproxy.uni-muenster.de:80'
    - name: auto_proxy
      value: 'http://www.uni-muenster.de/proxyforce.pac'
    - name: NO_PROXY
      value: 'localhost,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,.svc,10.14.20.42,10.14.20.44,10.14.20.45'
    - name: no_proxy
      value: 'localhost,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,.svc,10.14.20.42,10.14.20.44,10.14.20.45'
    - name: USE_PROXY
      value: 'yes'
    - name: use_proxy
      value: 'yes'

# Disable services not needed
configmapReload:
  prometheus:
    enabled: false

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: false

# ScienceMesh scrape configurations
extraScrapeConfigs: |
  - job_name: 'sciencemesh'
    scheme: 'https'
    # For testing, skip certificate verification
    tls_config:
      insecure_skip_verify: true
    # Adjust the proxy as needed
    proxy_url: 'http://wwwproxy.uni-muenster.de:80'

    file_sd_configs:
    - refresh_interval: 30s
      files:
        - '/etc/prometheus/sciencemesh/services.json'

  - job_name: 'sciencemesh-health-basic'
    scheme: 'https'
    metrics_path: /blackbox/probe
    # For testing, skip certificate verification
    tls_config:
      insecure_skip_verify: true
    # Adjust the proxy as needed
    proxy_url: 'http://wwwproxy.uni-muenster.de:80'

    params:
      module: [http_resp]

    file_sd_configs:
    - refresh_interval: 30s
      files:
        - '/etc/prometheus/sciencemesh/blackbox.json'

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: sciencemesh-test.uni-muenster.de

  - job_name: 'sciencemesh-health-auth'
    scheme: 'https'
    metrics_path: /blackbox/probe
    # For testing, skip certificate verification
    tls_config:
      insecure_skip_verify: true
    # Adjust the proxy as needed
    proxy_url: 'http://wwwproxy.uni-muenster.de:80'

    params:
      module: [http_basic_auth]

    file_sd_configs:
    - refresh_interval: 30s
      files:
        - '/etc/prometheus/sciencemesh/blackbox.json'

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: __param_target
        replacement: $1/ocm/invites
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: sciencemesh-test.uni-muenster.de
