# Server settings
server:
  ingress:
    enabled: true
    hosts:
      - prometheus.sciencemesh.uni-muenster.de
    tls:
      - secretName: sciencemesh-tls
        hosts:
          - prometheus.sciencemesh.uni-muenster.de
  persistentVolume:
    enabled: true
    storageClass: rbd
  global:
    scrape_interval: 30s
    scrape_timeout: 15s
    evaluation_interval: 30s
  extraArgs:
    web.external-url: 'https://prometheus.sciencemesh.uni-muenster.de'
    web.route-prefix: '/'
  extraVolumeMounts:
    - name: scrape-configs
      mountPath: /tmp/sciencemesh
  extraVolumes:
    - name: scrape-configs
      persistentVolumeClaim:
        claimName: prom-shared-data

serverFiles:
  recording_rules.yml:
    # -- REC_RULES --

# Disable services not needed
configmapReload:
  prometheus:
    enabled: false

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: false

rbac:
  create: false
