replicaCount: 1

image:
  repository: cs3org/revad
  pullPolicy: Always

http:
  service:
    port: 20080

grpc:
  service:
    port: 20099

# https://reva.link/docs/config/
configFiles:
  users.toml: |
    [shared]
    jwt_secret = "Pive-Fumkiu4"

    [grpc]
    address = "0.0.0.0:18000"

    [grpc.services.authprovider]
    auth_manager = "json"

    [grpc.services.authprovider.auth_managers.json]
    users = "users.demo.json"

    [grpc.services.userprovider]
    driver = "json"

    [grpc.services.userprovider.drivers.json]
    users = "users.demo.json"

  users.demo.json: |
    [
        {
            "id": {
                "opaque_id": "4c510ada-c86b-4815-8820-42cdf82c3d51",
                "idp": "https://sciencemesh-test.uni-muenster.de/api/"
            },
            "username": "einstein",
            "secret": "relativity",
            "mail": "einstein@example.org",
            "display_name": "Albert Einstein",
            "groups": ["sailing-lovers", "violin-haters", "physics-lovers"]
        },
        {
            "id": {
                "opaque_id": "f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c",
                "idp": "https://sciencemesh-test.uni-muenster.de/api/"
            },
            "username": "marie",
            "secret": "radioactivity",
            "mail": "marie@example.org",
            "display_name": "Marie Curie",
            "groups": ["radium-lovers", "polonium-lovers", "physics-lovers"]
        },
        {
            "id": {
                "opaque_id": "932b4540-8d16-481e-8ef4-588e4b6b151c",
                "idp": "https://sciencemesh-test.uni-muenster.de/api/"
            },
            "username": "richard",
            "secret": "superfluidity",
            "mail": "richard@example.org",
            "display_name": "Richard Feynman",
            "groups": ["quantum-lovers", "philosophy-haters", "physics-lovers"]
        }
    ]

  storage-oc.toml: |
    [shared]
    jwt_secret = "Pive-Fumkiu4"
    gatewaysvc = "localhost:19000"

    [grpc]
    address = "0.0.0.0:11000"

    [grpc.services.storageprovider]
    driver = "owncloud"
    mount_path = "/oc"
    mount_id = "123e4567-e89b-12d3-a456-426655440000"
    expose_data_server = true
    data_server_url = "https://sciencemesh-test.uni-muenster.de/api/data"

    [grpc.services.storageprovider.drivers.owncloud]
    datadirectory = "/var/tmp/reva/data"

    [http]
    address = "0.0.0.0:11001"

    [http.services.dataprovider]
    driver = "owncloud"
    temp_folder = "/var/tmp/reva/tmp"

    [http.services.dataprovider.drivers.owncloud]
    datadirectory = "/var/tmp/reva/data"

  storage-home.toml: |
    [shared]
    jwt_secret = "Pive-Fumkiu4"
    gatewaysvc = "localhost:19000"

    [grpc]
    address = "0.0.0.0:12000"

    [grpc.services.storageprovider]
    driver = "owncloud"
    mount_path = "/home"
    mount_id = "123e4567-e89b-12d3-a456-426655440000"
    expose_data_server = true
    data_server_url = "http://localhost:12001/data"
    enable_home_creation = true

    [grpc.services.storageprovider.drivers.owncloud]
    datadirectory = "/var/tmp/reva/data"
    enable_home = true

    [http]
    address = "0.0.0.0:12001"

    [http.services.dataprovider]
    driver = "owncloud"
    temp_folder = "/var/tmp/reva/tmp"

    [http.services.dataprovider.drivers.owncloud]
    datadirectory = "/var/tmp/reva/data"
    enable_home = true

  shares.toml: |
    [shared]
    jwt_secret = "Pive-Fumkiu4"

    [grpc]
    address = "0.0.0.0:17000"

    [grpc.services.usershareprovider]
    driver = "memory"

    [grpc.services.publicshareprovider]
    driver = "memory"

  providers.demo.json: |
    [
      {
          "domain": "cern.ch",
          "api_version": "0.0.1",
          "api_endpoint": "http://127.0.0.1:13001/ocm/",
          "webdav_endpoint": "http://127.0.0.1:13001/ocm/webdav/"
      },
      {
          "domain": "cesnet.cz",
          "api_version": "0.0.1",
          "api_endpoint": "http://127.0.0.1:13001/ocm/",
          "webdav_endpoint": "http://127.0.0.1:13001/ocm/webdav/"
      },
      {
          "domain": "example.org",
          "api_version": "0.0.1",
          "api_endpoint": "http://127.0.0.1:13001/ocm/",
          "webdav_endpoint": "http://127.0.0.1:13001/ocm/webdav/"
      },
      {
          "domain": "test.org",
          "api_version": "0.0.1",
          "api_endpoint": "http://127.0.0.1:13001/ocm/",
          "webdav_endpoint": "http://127.0.0.1:13001/ocm/webdav/"
      }
    ]

  ocmd.toml: |
    [shared]
    jwt_secret = "Pive-Fumkiu4"
    gatewaysvc = "localhost:19000"

    [grpc]
    address = "0.0.0.0:13000"

    [grpc.services.ocmcore]
    driver = "json"

    [grpc.services.ocmcore.drivers.json]
    #file = " /var/tmp/reva/shares_server_1.json"

    [grpc.services.ocminvitemanager]
    driver = "memory"

    [grpc.services.ocmshareprovider]
    driver = "json"

    [grpc.services.ocmshareprovider.drivers.json]
    #file = " /var/tmp/reva/shares_server_1.json"

    [grpc.services.ocmproviderauthorizer]
    driver = "json"

    [grpc.services.ocmproviderauthorizer.drivers.json]
    providers = "providers.demo.json"

    [http]
    enabled_services = ["ocmd"]
    enabled_middlewares = ["providerauthorizer", "cors"]
    address = "0.0.0.0:13001"

    [http.services.ocmd]
    prefix = "ocm"

    [http.middlewares.providerauthorizer]
    driver = "json"

    [http.middlewares.providerauthorizer.drivers.json]
    providers = "providers.demo.json"

    [http.middlewares.cors]

  revad.toml: |
    [shared]
    jwt_secret = "Pive-Fumkiu4"
    gatewaysvc = "localhost:19000"

    [grpc]
    address = "0.0.0.0:19000"

    [grpc.services.gateway]
    authregistrysvc = "localhost:19000"
    storageregistrysvc = "localhost:19000"
    preferencessvc = "localhost:18000"
    userprovidersvc = "localhost:18000"
    usershareprovidersvc = "localhost:17000"
    publicshareprovidersvc = "localhost:17000"
    ocmcoresvc = "localhost:13000"
    ocmshareprovidersvc = "localhost:13000"
    ocminvitemanagersvc = "localhost:13000"
    ocmproviderauthorizersvc = "localhost:13000"
    commit_share_to_storage_grant = true
    datagateway = "http://localhost:19001/data"
    transfer_shared_secret = "replace-me-with-a-transfer-secret" # for direct uploads
    transfer_expires = 6 # give it a moment
    #disable_home_creation_on_login = true

    [grpc.services.authregistry]
    driver = "static"

    [grpc.services.authregistry.drivers.static.rules]
    basic = "localhost:18000" # started with the users.toml
    bearer = "localhost:20099" # started with the frontend.toml

    [grpc.services.storageregistry]
    driver = "static"

    [grpc.services.storageregistry.drivers.static]
    home_provider = "/home"

    [grpc.services.storageregistry.drivers.static.rules]
    "/home" = "localhost:12000"

    "/oc" = "localhost:11000"
    "123e4567-e89b-12d3-a456-426655440000" = "localhost:11000"

    [http]
    address = "0.0.0.0:19001"

    [http.services.datagateway]
    transfer_shared_secret = "replaced-replace-me-with-a-transfer-secret"

  frontend.toml: |
    [shared]
    jwt_secret = "Pive-Fumkiu4"
    gatewaysvc = "localhost:19000"

    [grpc]
    address = "0.0.0.0:20099"

    [grpc.services.authprovider]
    auth_manager = "oidc"

    [grpc.services.authprovider.auth_managers.oidc]
    issuer = "https://sciencemesh-test.uni-muenster.de/api/"

    [http]
    address = "0.0.0.0:20080"

    [http.middlewares.cors]
    allow_credentials = true

    [http.services.wellknown]
    issuer = "https://sciencemesh-test.uni-muenster.de/api/"
    authorization_endpoint = "https://sciencemesh-test.uni-muenster.de/api/oauth2/auth"
    token_endpoint = "https://sciencemesh-test.uni-muenster.de/api/oauth2/token"
    revocation_endpoint = "https://sciencemesh-test.uni-muenster.de/api/oauth2/auth"
    introspection_endpoint = "https://sciencemesh-test.uni-muenster.de/api/oauth2/introspect"
    userinfo_endpoint = "https://sciencemesh-test.uni-muenster.de/api/oauth2/userinfo"

    [http.services.oidcprovider]
    prefix = "oauth2"
    issuer = "https://sciencemesh-test.uni-muenster.de/api/"

    [http.services.oidcprovider.clients.phoenix]
    id = "phoenix"
    redirect_uris = ["https://sciencemesh-test.uni-muenster.de/oidc-callback.html", "https://sciencemesh-test.uni-muenster.de/"]
    grant_types = ["implicit", "refresh_token", "authorization_code", "password", "client_credentials"]
    response_types = ["code"] # use authorization code flow, see https://developer.okta.com/blog/2019/05/01/is-the-oauth-implicit-flow-dead for details
    scopes = ["openid", "profile", "email", "offline"]
    public = true # force PKCS for public clients

    [http.services.ocdav]
    prefix = ""
    chunk_folder = "/var/tmp/reva/chunks"
    files_namespace = "/oc"
    webdav_namespace = "/home"

    [http.services.ocs]

    [http.services.helloworld]
    prefix = "hello"
    message = "Hello from WWU!"

    [http.services.mentix]
    prefix = "mentix"
    connector = "gocdb"
    exporters = ["webapi"]
    update_interval = "15m"

    [http.services.mentix.gocdb]
    address = "https://sciencemesh-test.uni-muenster.de/gocdb/"

    [http.services.mentix.webapi]
    endpoint = "/"

args:
    - "-dev-dir"
    - "."

workingDir: "/etc/revad/"
