# https://reva.link/docs/config/
configFiles:
  revad.toml: |
    [grpc.services.gateway]
    [grpc.services.storageregistry]
    [grpc.services.storageprovider]
    [grpc.services.authprovider]
    [grpc.services.authregistry]
    [grpc.services.userprovider]
    [grpc.services.usershareprovider]
    [grpc.services.publicshareprovider]

    [http.services.dataprovider]
    [http.services.prometheus]

    # WWU specifics --

    [http.services.helloworld]
    prefix = "hello"
    message = "Hello from WWU!"

    [http.services.mentix]
    connector = "gocdb"
    exporters = ["webapi", "prom_filesd"]
    update_interval = "15m"

    [http.services.mentix.gocdb]
    address = "https://sciencemesh-test.uni-muenster.de/gocdb/"

    [http.services.mentix.webapi]
    endpoint = "/"

    [http.services.mentix.prom_filesd]
    output_file = "/etc/revad/scrapes/services.json"

  users.json: |
    [
    	{
    		"id": {
    			"opaque_id": "wwu42",
    			"idp": "https://sciencemesh-test.uni-muenster.de/api"
    		},
    		"username": "wwu42",
    		"secret": "wwu42",
    		"mail": "daniel.mueller@uni-muenster.de",
    		"display_name": "Daniel Mueller",
    		"groups": ["sailing-lovers", "violin-haters", "physics-lovers"]
    	}
    ]

  providers.json: |
    [
    	{
    		"name": "cernbox",
    		"full_name": "CERNBox",
    		"organization": "CERN",
    		"domain": "https://cern.ch",
    		"homepage": "https://cernbox.web.cern.ch",
    		"description": "CERNBox provides cloud data storage to all CERN users.",
    		"services": [
    			{
    				"endpoint": {
    					"type": {
    						"name": "OCM",
    						"description": "CERNBox Open Cloud Mesh API"
    					},
    					"name": "CERNBox - OCM API",
    					"path": "https://sciencemesh.cernbox.cern.ch/iop/ocm/",
    					"isMonitored": true
    				},
    				"api_version": "0.0.1",
    				"host": "https://sciencemesh.cernbox.cern.ch/"
    			}
    		]
    	},
    	{
    		"name": "oc-cesnet",
    		"full_name": "ownCloud@CESNET",
    		"organization": "CESNET",
    		"domain": "https://cesnet.cz",
    		"homepage": "https://owncloud.cesnet.cz",
    		"description": "OwnCloud has been designed for individual users.",
    		"services": [
    			{
    				"endpoint": {
    					"type": {
    						"name": "OCM",
    						"description": "CESNET Open Cloud Mesh API"
    					},
    					"name": "CESNET - OCM API",
    					"path": "https://sciencemesh.cesnet.cz/ocm/",
    					"isMonitored": true
    				},
    				"api_version": "0.0.1",
    				"host": "https://sciencemesh.cesnet.cz/"
    			}
    		]
    	},
    	{
    		"name": "uni-muenster",
    		"full_name": "WWU University of Muenster",
    		"organization": "University of Muenster",
    		"domain": "https://uni-muenster.de",
    		"homepage": "https://uni-muenster.de",
    		"description": "WWU provides cloud storage to its students, faculty and researchers.",
    		"services": [
    			{
    				"endpoint": {
    					"type": {
    						"name": "OCM",
    						"description": "WWU Open Cloud Mesh API"
    					},
    					"name": "WWU - OCM API",
    					"path": "https://sciencemesh-test.uni-muenster.de/ocm/",
    					"isMonitored": true
    				},
    				"api_version": "0.0.1",
    				"host": "https://sciencemesh-test.uni-muenster.de/"
    			}
    		]
    	},
    	{
    		"name": "cubbit",
    		"full_name": "Cubbit",
    		"organization": "Cubbit",
    		"domain": "https://cubbit.io",
    		"homepage": "https://cubbit.io",
    		"description": "Cubbit provides distributed storage over a P2P network.",
    		"services": [
    			{
    				"endpoint": {
    					"type": {
    						"name": "OCM",
    						"description": "Cubbit Open Cloud Mesh API"
    					},
    					"name": "Cubbit - OCM API",
    					"path": "https://ocm.cubbit.io/ocm/",
    					"isMonitored": true
    				},
    				"api_version": "0.0.1",
    				"host": "https://ocm.cubbit.io/"
    			}
    		]
    	},
    	{
    		"name": "ailleron",
    		"full_name": "Ailleron - Software Mind",
    		"organization": "Ailleron",
    		"domain": "https://ailleron.com",
    		"homepage": "https://ailleron.com",
    		"description": "Ailleron is a Polish IT company providing software and storage solutions to its clients.",
    		"services": [
    			{
    				"endpoint": {
    					"type": {
    						"name": "OCM",
    						"description": "Ailleron Open Cloud Mesh API"
    					},
    					"name": "Ailleron - OCM API",
    					"path": "http://cs3mesh.softwaremind.com:19000/ocm/",
    					"isMonitored": true
    				},
    				"api_version": "0.0.1",
    				"host": "http://cs3mesh.softwaremind.com:19000/"
    			}
    		]
    	},
    	{
    		"name": "surfsara",
    		"full_name": "Surfsara",
    		"organization": "Surfsara",
    		"domain": "https://surfsara.nl",
    		"homepage": "https://surfsara.nl",
    		"description": "OwnCloud has been designed for individual users.",
    		"services": [
    			{
    				"endpoint": {
    					"type": {
    						"name": "OCM",
    						"description": "Surfsara Open Cloud Mesh API"
    					},
    					"name": "Surfsara - OCM API",
    					"path": "https://app.cs3mesh-iop.k8s.surfsara.nl/ocm/",
    					"isMonitored": true
    				},
    				"api_version": "0.0.1",
    				"host": "https://app.cs3mesh-iop.k8s.surfsara.nl/"
    			}
    		]
    	}
    ]
