extraVolumeMounts:
  - name: scrape-configs
    mountPath: /etc/revad/scrapes

extraVolumes:
  - name: scrape-configs
    persistentVolumeClaim:
      claimName: prom-shared-data

configFiles:
  revad.toml: |
    [grpc.services.gateway]
    datagateway = "https://sciencemesh-test.uni-muenster.de/api/datagateway"

    [grpc.services.storageregistry]
    [grpc.services.storageprovider]
    data_server_url = "https://sciencemesh-test.uni-muenster.de/api/data"

    [grpc.services.authprovider]
    [grpc.services.authregistry]
    [grpc.services.userprovider]
    [grpc.services.usershareprovider]
    [grpc.services.publicshareprovider]
    [grpc.services.ocmcore]
    [grpc.services.ocmshareprovider]
    [grpc.services.ocminvitemanager]
    [grpc.services.ocmproviderauthorizer]

    [http.services.datagateway]
    [http.services.dataprovider]
    [http.services.prometheus]
    [http.services.ocmd]

    # WWU specifics --

    [http.services.helloworld]
    prefix = "hello"
    message = "Hello from WWU!"

    [http.services.mentix]
    connector = "gocdb"
    exporters = ["webapi", "prom_filesd"]
    update_interval = "15m"

    [http.services.mentix.gocdb]
    address = "https://sciencemesh-test.uni-muenster.de/gocdb/"

    [http.services.mentix.webapi]
    endpoint = "/"

    [http.services.mentix.prom_filesd]
    output_file = "/etc/revad/scrapes/services.json"

  users.json: |
    [
    	{
    		"id": {
    			"opaque_id": "holger1234",
    			"idp": "https://uni-muenster.de"
    		},
    		"username": "holger",
    		"secret": "holgerpass",
    		"mail": "holger@uni-muenster.de",
    		"display_name": "Holger",
    		"groups": ["sailing-lovers", "violin-haters", "physics-lovers"]
    	},
    	{
    		"id": {
    			"opaque_id": "daniel5678",
    			"idp": "https://uni-muenster.de"
    		},
    		"username": "daniel",
    		"secret": "danielpass",
    		"mail": "daniel@uni-muenster.de",
    		"display_name": "Daniel",
    		"groups": ["radium-lovers", "polonium-lovers", "physics-lovers"]
    	}
    ]

  ocm-providers.json: |
    [
    	{
    		"name": "cernbox",
    		"full_name": "CERNBox",
    		"organization": "CERN",
    		"domain": "https://cern.ch",
    		"homepage": "https://cernbox.web.cern.ch",
    		"description": "CERNBox provides cloud data storage to all CERN users.",
    		"services": [
    			{
    				"endpoint": {
    					"type": {
    						"name": "OCM",
    						"description": "CERNBox Open Cloud Mesh API"
    					},
    					"name": "CERNBox - OCM API",
    					"path": "https://sciencemesh.cernbox.cern.ch/iop/ocm/",
    					"isMonitored": true
    				},
    				"api_version": "0.0.1",
    				"host": "https://sciencemesh.cernbox.cern.ch/iop/"
    			}
    		]
    	},
    	{
    		"name": "oc-cesnet",
    		"full_name": "ownCloud@CESNET",
    		"organization": "CESNET",
    		"domain": "https://cesnet.cz",
    		"homepage": "https://owncloud.cesnet.cz",
    		"description": "OwnCloud has been designed for individual users.",
    		"services": [
    			{
    				"endpoint": {
    					"type": {
    						"name": "OCM",
    						"description": "CESNET Open Cloud Mesh API"
    					},
    					"name": "CESNET - OCM API",
    					"path": "https://sciencemesh.cesnet.cz/iop/ocm/",
    					"isMonitored": true
    				},
    				"api_version": "0.0.1",
    				"host": "https://sciencemesh.cesnet.cz/iop/"
    			}
    		]
    	},
    	{
    		"name": "uni-muenster",
    		"full_name": "WWU University of Muenster",
    		"organization": "University of Muenster",
    		"domain": "https://uni-muenster.de",
    		"homepage": "https://uni-muenster.de",
    		"description": "WWU provides cloud storage to its students, faculty and researchers.",
    		"services": [
    			{
    				"endpoint": {
    					"type": {
    						"name": "OCM",
    						"description": "WWU Open Cloud Mesh API"
    					},
    					"name": "WWU - OCM API",
    					"path": "https://sciencemesh-test.uni-muenster.de/api/ocm/",
    					"isMonitored": true
    				},
    				"api_version": "0.0.1",
    				"host": "https://sciencemesh-test.uni-muenster.de/api/"
    			}
    		]
    	},
    	{
    		"name": "cubbit",
    		"full_name": "Cubbit",
    		"organization": "Cubbit",
    		"domain": "https://cubbit.io",
    		"homepage": "https://cubbit.io",
    		"description": "Cubbit provides distributed storage over a P2P network.",
    		"services": [
    			{
    				"endpoint": {
    					"type": {
    						"name": "OCM",
    						"description": "Cubbit Open Cloud Mesh API"
    					},
    					"name": "Cubbit - OCM API",
    					"path": "https://sciencemesh.cubbit.io/ocm/",
    					"isMonitored": true
    				},
    				"api_version": "0.0.1",
    				"host": "https://sciencemesh.cubbit.io/"
    			}
    		]
    	},
    	{
    		"name": "ailleron",
    		"full_name": "Ailleron - Software Mind",
    		"organization": "Ailleron",
    		"domain": "https://ailleron.com",
    		"homepage": "https://ailleron.com",
    		"description": "Ailleron is a Polish IT company providing software and storage solutions to its clients.",
    		"services": [
    			{
    				"endpoint": {
    					"type": {
    						"name": "OCM",
    						"description": "Ailleron Open Cloud Mesh API"
    					},
    					"name": "Ailleron - OCM API",
    					"path": "https://cs3mesh.softwaremind.com/iop/ocm/",
    					"isMonitored": true
    				},
    				"api_version": "0.0.1",
    				"host": "https://cs3mesh.softwaremind.com/iop/"
    			}
    		]
    	},
    	{
    		"name": "surfsara",
    		"full_name": "Surfsara",
    		"organization": "Surfsara",
    		"domain": "https://surfsara.nl",
    		"homepage": "https://surfsara.nl",
    		"description": "OwnCloud has been designed for individual users.",
    		"services": [
    			{
    				"endpoint": {
    					"type": {
    						"name": "OCM",
    						"description": "Surfsara Open Cloud Mesh API"
    					},
    					"name": "Surfsara - OCM API",
    					"path": "https://app.cs3mesh-iop.k8s.surfsara.nl/iop/ocm/",
    					"isMonitored": true
    				},
    				"api_version": "0.0.1",
    				"host": "https://app.cs3mesh-iop.k8s.surfsara.nl/iop/"
    			}
    		]
    	}
    ]
