apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o=./k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: gocdb-database
  name: gocdb-database
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: gocdb-database
status:
  loadBalancer: {}
