modules:
  http_ping:
    # Ping via HTTP; do not check the actual HTTP status, just ensure that the host is reachable through HTTP
    # Note: Request must be routed through the WWU proxy
    prober: nagios
    timeout: 10s
    nagios:
      check: check_http
      args:
        - -H $TARGET_HOST$
        - -u $TARGET_PATH$
        - -S
        - -N
        - -e HTTP
        - -w 3.0
        - -c 8.0
        - -t 10

  iop_login:
    # Try logging in to the IOP using the omnipresent 'test' user
    prober: nagios
    timeout: 10s
    nagios:
      check: check_ioplogin
      args:
        - -target=$TARGET$
        - -user=test
        - -pass=testpass
