siteaccounts:
  url: http://iop-gateway:19001/siteacc
  authentication:
    username: daniel
    password: danielpass
  security:
    creds_passphrase: "ThisIs5O!S3cr3tY0uW1LLN3vRGue$$!"

modules:
  http_ping:
    # Ping via HTTP; do not check the actual HTTP status, just ensure that the host is reachable through HTTP
    # Note: Request must be routed through the WWU proxy
    prober: nagios
    timeout: 15s
    nagios:
      check: check_http
      args:
        - -H $TARGET_HOST$
        - -u $TARGET_PATH$
        - -S
        - -N
        - -e HTTP
        - -w 3.0
        - -c 8.0
        - -t 10

  iop_login:
    # Try logging in to the IOP
    prober: nagios
    timeout: 15s
    nagios:
      check: check_ioplogin
      args:
        - -target=$TARGET$
        - -user=$TESTCLIENT_ID$
        - -pass=$TESTCLIENT_SECRET$

  network:
    # Try reaching the IOP
    prober: nagios
    timeout: 15s
    nagios:
      check: check_network
      args:
        - -target=$TARGET$

  fs_operations:
    # Perform various file system operations on the IOP
    prober: nagios
    timeout: 15s
    nagios:
      check: check_fsoperations
      args:
        - -target=$TARGET$
        - -user=$TESTCLIENT_ID$
        - -pass=$TESTCLIENT_SECRET$

  fs_speed:
    # Measure the speed of several file system operations on the IOP
    prober: nagios
    timeout: 30s
    nagios:
      check: check_fsspeed
      args:
        - -target=$TARGET$
        - -user=$TESTCLIENT_ID$
        - -pass=$TESTCLIENT_SECRET$
