modules:
  http_ping:
    # Ping via HTTP; do not check the actual HTTP status, just ensure that the host is reachable through HTTP
    # Note: Request must be routed through the WWU proxy
    prober: nagios
    timeout: 5s
    nagios:
      check: check_http
      args:
        - -H wwwproxy.uni-muenster.de:80
        - -u $TARGET$
        - -N
        - -e HTTP
        - -w 3.0
        - -c 5.0
        - -t 5
      proxy_url: http://wwwproxy.uni-muenster.de:80

  iop_login:
    # Try logging in to the IOP using the omnipresent 'test' user
    prober: nagios
    timeout: 5s
    nagios:
      check: check_ioplogin
      args:
        - -target=$TARGET$
        - -user=test
        - -pass=testpass
      proxy_url: http://wwwproxy.uni-muenster.de:80
