# gRPC services --
[grpc.services.gateway]
datagateway = "https://sciencemesh-test.uni-muenster.de/api/datagateway"
appprovidersvc = "iop-gateway:19000"
appregistry = "iop-gateway:19000"
commit_share_to_storage_grant = true
commit_share_to_storage_ref = true

[grpc.services.storageregistry]
[grpc.services.storageregistry.drivers.static]
home_provider = "/home"

[grpc.services.storageregistry.drivers.static.rules]
"/home" = "iop-storageprovider-home:17000"
"/reva" = "iop-storageprovider-reva:18000"
"123e4567-e89b-12d3-a456-426655440000" = "iop-storageprovider-reva:18000"

[grpc.services.authprovider]
[grpc.services.authregistry]
[grpc.services.userprovider]
[grpc.services.usershareprovider]
[grpc.services.publicshareprovider]
[grpc.services.ocmcore]

[grpc.services.ocmshareprovider]
[grpc.services.ocmshareprovider.drivers.json]
insecure_connections = true

[grpc.services.ocminvitemanager]
[grpc.services.ocminvitemanager.drivers.json]
insecure_connections = true

[grpc.services.ocmproviderauthorizer]
driver = "mentix"
[grpc.services.ocmproviderauthorizer.drivers.mentix]
url = "https://sciencemesh-test.uni-muenster.de/api/mentix/cs3"
verify_request_hostname = true
insecure = false
timeout = 10
refresh = 900

[grpc.services.appprovider]
driver = "demo"
wopiurl = "https://sciencemesh-test.uni-muenster.de/"

[grpc.services.appregistry]
driver = "static"
[grpc.services.appregistry.static.rules]
"text/plain" = "iop-gateway:19000"
"text/markdown" = "iop-gateway:19000"
"application/vnd.oasis.opendocument.text" = "iop-gateway:19000"
"application/vnd.oasis.opendocument.spreadsheet" = "iop-gateway:19000"
"application/vnd.oasis.opendocument.presentation" = "iop-gateway:19000"

# HTTP services --
[http.services.datagateway]
[http.services.prometheus]

[http.services.ocmd]
mesh_directory_url = "https://sciencemesh.cesnet.cz/iop/meshdir"
[http.services.ocmd.smtp_credentials]
sender_mail = "daniel.mueller@uni-muenster.de"
smtp_server = "mail.uni-muenster.de"
smtp_port = 25
disable_auth = true

[http.services.sysinfo]

[http.middlewares.providerauthorizer]
driver = "mentix"
[http.middlewares.providerauthorizer.drivers.mentix]
url = "https://sciencemesh-test.uni-muenster.de/api/mentix/cs3"
insecure = false
timeout = 10
refresh = 900

# Mentix configuration --
[http.services.mentix]
connector = "gocdb"
exporters = ["webapi", "cs3api", "siteloc", "prom_filesd"]
update_interval = "15m"
[http.services.mentix.gocdb]
address = "https://sciencemesh-test.uni-muenster.de/gocdb/"
[http.services.mentix.prom_filesd]
output_file = "/etc/revad/scrapes/services.json"
