# General jobs
- job_name: 'sciencemesh-metrics'
  scheme: 'https'
  proxy_url: 'http://wwwproxy.uni-muenster.de:80' # Adjust the proxy as needed

  file_sd_configs:
  - refresh_interval: 30s
    files:
      - '/etc/prometheus/sciencemesh/services.json'

  relabel_configs:
    - source_labels: [__meta_site]
      target_label: site
    - source_labels: [__meta_site_type]
      target_label: site_type
    - source_labels: [__meta_country]
      target_label: country
    - source_labels: [__meta_service_type]
      target_label: service_type

# Blackbox jobs
- job_name: 'sciencemesh-health-basic'
  scheme: 'http'
  metrics_path: /probe

  params:
    module: [http_resp]

  file_sd_configs:
  - refresh_interval: 30s
    files:
      - '/etc/prometheus/sciencemesh/blackbox.json'

  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter-prometheus-blackbox-exporter:9115
    - source_labels: [__meta_site]
      target_label: site
    - source_labels: [__meta_site_type]
      target_label: site_type
    - source_labels: [__meta_country]
      target_label: country
    - source_labels: [__meta_service_type]
      target_label: service_type

- job_name: 'sciencemesh-health-auth'
  scheme: 'http'
  metrics_path: /probe

  params:
    module: [http_basic_auth]

  file_sd_configs:
  - refresh_interval: 30s
    files:
      - '/etc/prometheus/sciencemesh/blackbox.json'

  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: __param_target
      replacement: $1/ocm/invites
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter-prometheus-blackbox-exporter:9115
    - source_labels: [__meta_site]
      target_label: site
    - source_labels: [__meta_site_type]
      target_label: site_type
    - source_labels: [__meta_country]
      target_label: country
    - source_labels: [__meta_service_type]
      target_label: service_type
