# -- General Jobs --

- job_name: 'sciencemesh-metrics'
  scheme: 'https'
  proxy_url: 'http://wwwproxy.uni-muenster.de:80' # Adjust the proxy as needed

  file_sd_configs:
  - refresh_interval: 30s
    files:
      - '/etc/prometheus/sciencemesh/services.json'

  relabel_configs:
    - source_labels: [__meta_mentix_site]
      target_label: site
    - source_labels: [__meta_mentix_site_id]
      target_label: site_id
    - source_labels: [__meta_mentix_site_type]
      target_label: site_type
    - source_labels: [__meta_mentix_country]
      target_label: country
    - source_labels: [__meta_mentix_service_type]
      target_label: service_type


# -- Health Check Jobs --

- job_name: 'sciencemesh-hcheck-http-ping'
  scheme: 'http'
  metrics_path: /probe

  params:
    module: [http_ping]

  file_sd_configs:
  - refresh_interval: 30s
    files:
      - '/etc/prometheus/sciencemesh/blackbox.json'

  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter-prometheus-blackbox-exporter:9115
    - source_labels: [__meta_mentix_site]
      target_label: site
    - source_labels: [__meta_mentix_site_id]
      target_label: site_id
    - source_labels: [__meta_mentix_site_type]
      target_label: site_type
    - source_labels: [__meta_mentix_country]
      target_label: country
    - source_labels: [__meta_mentix_service_type]
      target_label: service_type

- job_name: 'sciencemesh-hcheck-iop-login'
  scheme: 'http'
  metrics_path: /probe

  params:
    module: [iop_login]

  file_sd_configs:
  - refresh_interval: 30s
    files:
      - '/etc/prometheus/sciencemesh/blackbox.json'

  relabel_configs:
    - source_labels: [__meta_mentix_host, __meta_mentix_grpc_port]
      separator: ':'
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter-prometheus-blackbox-exporter:9115
    - source_labels: [__meta_mentix_site]
      target_label: site
    - source_labels: [__meta_mentix_site_id]
      target_label: site_id
    - source_labels: [__meta_mentix_site_type]
      target_label: site_type
    - source_labels: [__meta_mentix_country]
      target_label: country
    - source_labels: [__meta_mentix_service_type]
      target_label: service_type
