[grpc.services.gateway]
datagateway = "https://sciencemesh-test.uni-muenster.de/api/datagateway"
[grpc.services.storageregistry]
[grpc.services.storageprovider]
data_server_url = "https://sciencemesh-test.uni-muenster.de/api/data"
[grpc.services.authprovider]
[grpc.services.authregistry]
[grpc.services.userprovider]
[grpc.services.usershareprovider]
[grpc.services.publicshareprovider]
[grpc.services.ocmcore]
[grpc.services.ocmshareprovider]
[grpc.services.ocmshareprovider.drivers.json]
insecure_connections = true
[grpc.services.ocminvitemanager]
[grpc.services.ocminvitemanager.drivers.json]
insecure_connections = true
[grpc.services.ocmproviderauthorizer]
driver = "mentix"
verify_request_hostname = true
[grpc.services.ocmproviderauthorizer.drivers.mentix]
url = "https://sciencemesh-test.uni-muenster.de/api/mentix/cs3"
verify_request_hostname = true
insecure = false
refresh = 300

[http.services.datagateway]
[http.services.dataprovider]
[http.services.prometheus]
[http.services.ocmd]
[http.services.ocmd.smtp_credentials]
sender_mail = "daniel.wwu.it@gmail.com"
smtp_server = "smtp.gmail.com"
smtp_port = 587
disable_auth = true

# WWU specifics --

[http.services.helloworld]
prefix = "hello"
message = "Hello from WWU!"

[http.services.mentix]
connector = "gocdb"
exporters = ["webapi", "cs3api", "siteloc", "prom_filesd"]
update_interval = "15m"

[http.services.mentix.gocdb]
address = "https://sciencemesh-test.uni-muenster.de/gocdb/"

[http.services.mentix.prom_filesd]
output_file = "/etc/revad/scrapes/services.json"
