[grpc]
address = "0.0.0.0:17000"

[grpc.services.storageprovider]
driver = "localhome"
mount_path = "/home"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
data_server_url = "http://iop-storageprovider-home:17001/data"
disable_tus = true

[http]
address = "0.0.0.0:17001"

[http.services.dataprovider]
driver = "localhome"
disable_tus = true
