# -- Reva daemon --
revad:
  extraVolumeMounts:
    - name: scrape-configs
      mountPath: /etc/revad/scrapes

  extraVolumes:
    - name: scrape-configs
      persistentVolumeClaim:
        claimName: prom-shared-data

  env:
    # Adjust the proxy settings as needed
    - name: HTTPS_PROXY
      value: 'http://wwwproxy.uni-muenster.de:80'
    - name: HTTP_PROXY
      value: 'http://wwwproxy.uni-muenster.de:80'
    - name: AUTO_PROXY
      value: 'http://www.uni-muenster.de/proxyforce.pac'
    - name: https_proxy
      value: 'http://wwwproxy.uni-muenster.de:80'
    - name: http_proxy
      value: 'http://wwwproxy.uni-muenster.de:80'
    - name: auto_proxy
      value: 'http://www.uni-muenster.de/proxyforce.pac'
    - name: NO_PROXY
      value: 'localhost,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,.svc,10.14.20.42,10.14.20.44,10.14.20.45'
    - name: no_proxy
      value: 'localhost,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,.svc,10.14.20.42,10.14.20.44,10.14.20.45'
    - name: USE_PROXY
      value: 'yes'
    - name: use_proxy
      value: 'yes'

# -- WOPI server --
wopiserver:
  enabled: false
