{
 "title": "General statistics",
 "description": "Various ScienceMesh statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Notice",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h3 style=\"text-align: center; color: #3F92CB;\">\r\n    This dashboard is still work-in-progress!\r\n</h3>"
   }
  },
  {
   "title": "User distribution by country",
   "type": "grafana-worldmap-panel",
   "description": "Displays the distribution of ScienceMesh users across the world",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 2 },
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(country) (avg_over_time(revad_cs3_org_sciencemesh_site_total_num_users[5m]))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Site locations",
   "type": "grafana-worldmap-panel",
   "description": "Displays the locations of all sites in the ScienceMesh",
   "gridPos": { "h": 14, "w": 9, "x": 10, "y": 2 },
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(revad_sys_info[5m])  ",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "Site information",
   "type": "table",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 2 },
   "targets": [
    {
     "expr": "avg_over_time(revad_sys_info[5m])",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Users per site",
   "type": "bargauge",
   "description": "Displays the number of users per site",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(avg_over_time(revad_cs3_org_sciencemesh_site_total_num_users[5m]))",
     "legendFormat": "{{site}} ({{country}})"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "description": "Displays the total number of all users",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg_over_time(revad_cs3_org_sciencemesh_site_total_num_users[5m])"
    }
   ]
  },
  {
   "title": "Storage per site",
   "type": "gauge",
   "description": "Displays the storage per site",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(avg_over_time(revad_cs3_org_sciencemesh_site_total_amount_storage[5m]))",
     "legendFormat": "{{site}} ({{country}})"
    }
   ]
  },
  {
   "title": "Total storage",
   "type": "stat",
   "description": "Displays the total storage of all sites",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg_over_time(revad_cs3_org_sciencemesh_site_total_amount_storage[5m])"
    }
   ]
  }
 ]
}