{
 "title": "Health monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sites", "label": "Sites", "query": { "query": "sciencemesh_hcheck_site_status" } }
  ]
 },
 "panels": [
  {
   "title": "Site status",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sciencemesh_hcheck_site_status{status_type=\"RESULT\"}"
    },
    {
     "expr": "sciencemesh_hcheck_site_status{status_type=\"AVAIL\"}"
    },
    {
     "expr": "sciencemesh_hcheck_site_status{status_type=\"RELIAB\"}"
    }
   ]
  },
  {
   "title": "Service status: $sites",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "repeat": "sites",
   "targets": [
    {
     "expr": "sciencemesh_hcheck_service_status{site_id=\"$sites\", status_type=\"RESULT\"}"
    },
    {
     "expr": "sciencemesh_hcheck_service_status{site_id=\"$sites\", status_type=\"AVAIL\"}"
    }
   ]
  },
  {
   "title": "Check status: $sites",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "repeat": "sites",
   "targets": [
    {
     "expr": "probe_nagios_result{site_id=\"$sites\"}"
    }
   ]
  },
  {
   "title": "Site summary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(status_type) (sciencemesh_hcheck_site_status{status_type=\"OK\"} / 1)",
     "legendFormat": "Healthy"
    },
    {
     "expr": "sum by(status_type) (sciencemesh_hcheck_site_status{status_type=\"WARN\"} / 2)",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum by(status_type) (sciencemesh_hcheck_site_status{status_type=\"CRIT\"} / 3)",
     "legendFormat": "Critical"
    }
   ]
  }
 ]
}