# docker-compose.yml -- Set up all necessary containers to run a GOCDB instance
#
# Author:   Daniel Mueller/University of Muenster (daniel.mueller@uni-muenster.de)
# Date:     2020-04-22
# Version:  0.1
#
# Note:     This file is considered experimental and should be used with care.
#           It is neither meant to be efficient nor secure.
version: "3.4"

# GOCDB is delivered via two containers: A database and a webserver running the GOCDB instance
services:
    # Database server (MariaDB)
    database:
        image: mariadb:5
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: oihwnthnwent7u2
        volumes:
            - db:/var/lib/mysql
            - ./sql/:/docker-entrypoint-initdb.d:ro

    # Webserver (Apache + PHP 5) running the GOCDB instance
    webserver:
        build: webserver
        restart: always
        depends_on:
            - database
        volumes:
            - ./html:/var/www/html
        ports:
            - 80:80

volumes:
    db:
