# docker-compose.dev.yml -- Set up all necessary containers to run a GOCDB instance
#
# Development version: Mounts html and sql directories to host

version: "3.4"

# GOCDB is delivered via two containers: A database and a webserver running the GOCDB instance
services:
    # Database server (MariaDB)
    gocdb-database:
        image: mariadb:5
        container_name: "gocdb-database"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: oihwnthnwent7u2
        volumes:
            - db:/var/lib/mysql
            - ./database/sql/:/docker-entrypoint-initdb.d:ro
        ports:
            - 3306:3306

    # Webserver (Apache + PHP 5) running the GOCDB instance
    gocdb-webserver:
        build:
            context: ./webserver
            dockerfile: Dockerfile.dev
        container_name: "gocdb-webserver"
        restart: always
        depends_on:
            - gocdb-database
        environment:
            GOCDB_DATABASE_SERVER: gocdb-database
        volumes:
            - ./webserver/html.dev:/var/www/html
        ports:
            - 8080:80

volumes:
    db:
