apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "revad.fullname" . }}
  labels:
    {{- include "revad.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "revad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "revad.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.http.port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpc.port }}
              protocol: TCP
          command:
            - /go/bin/revad
          args:
              - "-c"
              - "/etc/revad/revad.toml"
              - "-p"
              - "/var/run/revad.pid"
          volumeMounts:
            - name: {{ include "revad.fullname" . }}-configfiles
              mountPath: /etc/revad/
            - name: {{ include "revad.fullname" . }}-datadir
              mountPath: /var/tmp/reva/
            {{- if .Values.extraVolumeMounts }}
              {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          {{- if .Values.env }}
          env:
              {{ toYaml .Values.env | nindent 12}}
          {{- end }}
      volumes:
        - name: {{ include "revad.fullname" . }}-configfiles
          configMap:
            name: {{ template "revad.fullname" . }}-config
        # TODO(SamuAlfageme): allow PersistentVolmeClaim custom Value
        - name: {{ include "revad.fullname" . }}-datadir
          emptyDir: {}
        {{- if .Values.extraVolumes }}
          {{ toYaml .Values.extraVolumes | nindent 8}}
        {{- end }}
