apiVersion: v1
kind: Service
metadata:
  name: {{ include "revad.fullname" . }}
  labels:
    {{- include "revad.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.http.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.grpc.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.dataprovider.service.port }}
      targetPort: dataprovider
      protocol: TCP
      name: dataprovider
  selector:
    {{- include "revad.selectorLabels" . | nindent 4 }}
