replicaCount: 1

image:
  repository: cs3org/revad
  pullPolicy: IfNotPresent

http:
  service:
    port: 20080

grpc:
  service:
    port: 20099

dataprovider:
  service:
    port: 11001

# https://reva.link/docs/config/
configFiles:
  revad.toml: |
    [shared]
    jwt_secret = "mysecret"

    [http]
    address = "0.0.0.0:20080"

    [http.services.prometheus]

    [grpc]
    address = "0.0.0.0:20099"

args: []
workingDir: ""

