global:
  # Global settings
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    scheme: 'http'
    metrics_path: '/metrics'

    static_configs:
    - targets: ['localhost:9090']

  # Read all ScienceMesh scrape targets from any files located in /etc/prometheus/sciencemesh/
  - job_name: 'sciencemesh'
    scheme: 'https'
    metrics_path: '/metrics'

    file_sd_configs:
      - refresh_interval: 30s
        files:
        - '/etc/prometheus/sciencemesh/*.json'
